lamorel_args:
  log_level: debug
  distributed_setup_args:
    n_rl_processes: 1
    n_llm_processes: 1
  accelerate_args:
    config_file: accelerate/default_config.yaml
    machine_rank: 0
    num_machines: 1
    num_processes: 2
    cpu:
  llm_args:
    model_type: causal
    model_path: distilgpt2
    model_parallelism_size: 1
    minibatch_size: 4
    synchronize_gpus_after_scoring: false
    empty_cuda_cache_after_scoring: false
  updater_args:
rl_script_args:
  path: ???
  task_idx: 13
  num_steps: 100
  max_episode_steps: 3
  simplification_str: easy
